const swaggerAutogen = require("swagger-autogen")();
const outputFile = "./swagger_output.json";
const endpoints = ["./src/routes/index.ts"];

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module: To be, or not to be: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Todos",
      description: "Endpoints that exposes to dos info",
    },
    {
      name: "Posts",
      description: "Endpoints that exposes posts",
    },
  ],
  definitions: {  
    Todos: {
      userId: 1,
      id: 1,
      title: "delectus aut autem",
      completed: false,
    },
    Posts: {
      userId: 2,
      id: 2,
      title:
        "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
      body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    },
  },
};

swaggerAutogen(outputFile, endpoints, doc)
// .then(() => {
  // require("./src/app");
  // require("C:\\Users\\Usuario\\Desktop\\pruebas-eco-18\\src\\app.ts");
// })